engine:
  type: "in_memory"
wal:
  flushing_batch_length: 100
  flushing_batch_timeout: "10ms"
  max_segment_size: "10MB"
  data_directory: "/data/wal"
network:
  address: "127.0.0.1:3223"
  max_connections: 100
logging:
  json: false
  level: "info"
  output: "/log/output.log"