name: CI/CD

on: push
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'

      - name: Check out code
        uses: actions/checkout@v4

      - name: linter
        run: make lint

      - name: test
        run: make test
